spring:
  application:
    name: audition-api
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true

server:
  max-http-request-header-size: 16KB

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

audition:
  api:
    base-url: https://jsonplaceholder.typicode.com
    posts-path: /posts
    comments-path: /comments
    circuit-breaker-name: auditionApi
    connect-timeout-ms: 5000
    read-timeout-ms: 10000

resilience4j:
  circuitbreaker:
    instances:
      "[${audition.api.circuit-breaker-name}]":
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 2s
        registerHealthIndicator: true
  retry:
    instances:
      "[${audition.api.circuit-breaker-name}]":
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpClientErrorException$TooManyRequests
  timelimiter:
    instances:
      "[${audition.api.circuit-breaker-name}]":
        timeoutDuration: 10s
